DATASET:
  TRANSFORMS:
    CENTER_CROP: null
    RESIZE:
    - 224
    - 224
TRAINING:
  MODEL:
    NAME: MaxVit
    REGISTRY: PIECE_CLASSIFIER
_BASE_: config://piece_classifier/_base_pretrained.yaml
