_BASE_: config://piece_classifier/_base.yaml

TRAINING:
  PHASES:
    - EPOCHS: 2
      OPTIMIZER:
        LEARNING_RATE: 0.001
        NAME: AdamW
      PARAMS: head
    - EPOCHS: 4
      OPTIMIZER:
        LEARNING_RATE: 0.0001
        NAME: AdamW
      PARAMS: head
