DATASET:
  TRANSFORMS:
    CENTER_CROP: null
    RESIZE:
    - 224
    - 224
TRAINING:
  MODEL:
    NAME: SwinTV2
    REGISTRY: OCCUPANCY_CLASSIFIER
_BASE_: config://occupancy_classifier/_base_pretrained_vit.yaml
