DATASET:
  TRANSFORMS:
    CENTER_CROP: null
    RESIZE:
    - 100
    - 200
TRAINING:
  MODEL:
    NAME: DLResNet
    REGISTRY: PIECE_SEGMENTER
_BASE_: config://piece_segmenter/_base_pretrained.yaml
